// sipmap — created by MUDIT AGRAWAL (muditagrawal2007) — MIT licensed
// /help — list all available commands.

module.exports = {
  name: 'help',
  description: 'List all available commands',
  requiresMaintainer: false,
  async execute(context) {
    const body = [
      '👋 Hi! I\'m **sipmap**, your friendly contributor helper.',
      '',
      '**Commands anyone can run:**',
      '| Command | What it does |',
      '|---|---|',
      '| `:sipmap /help` | Show this message |',
      '| `:sipmap /test` | Run process-testing digest on this PR/issue |',
      '| `:sipmap /status` | Summarize CI check runs |',
      '| `:sipmap /lint` | Lint PR contents |',
      '| `:sipmap /describe` | Validate description against template |',
      '| `:sipmap /size` | Flag oversized PRs |',
      '| `:sipmap /secrets` | Heuristic secret scan |',
      '| `:sipmap /deps` | Detect dependency changes |',
      '| `:sipmap /branch` | Validate branch name |',
      '| `:sipmap /commits` | Validate commit messages |',
      '| `:sipmap /title` | Validate PR/issue title |',
      '| `:sipmap /docs` | Check docs updated for code changes |',
      '| `:sipmap /tests` | Check tests updated for source changes |',
      '| `:sipmap /approvals` | Show approval status |',
      '| `:sipmap /claim` | Self-assign this issue |',
      '| `:sipmap /unclaim` | Release this issue |',
      '| `:sipmap /thanks @user` | Manual kudos |',
      '| `:sipmap /metrics @user` | Show contributor stats |',
      '| `:sipmap /label-list` | List all repo labels |',
      '| `:sipmap /contributors` | Top 10 contributors by merged PRs |',
      '',
      '**Maintainer commands** (require maintain/admin access):',
      '| Command | What it does |',
      '|---|---|',
      '| `:sipmap /assign @user` | Assign reviewer |',
      '| `:sipmap /unassign @user` | Remove reviewer |',
      '| `:sipmap /good-first-issue` | Apply `good first issue` label |',
      '| `:sipmap /help-wanted` | Apply `help wanted` label |',
      '| `:sipmap /label <names>` | Apply labels |',
      '| `:sipmap /unlabel <names>` | Remove labels |',
      '| `:sipmap /priority <low|med|high>` | Set priority label |',
      '| `:sipmap /review` | Ping maintainers |',
      '| `:sipmap /note <text>` | Add a maintainer note |',
      '| `:sipmap /close` | Close with reason |',
      '| `:sipmap /reopen` | Reopen with reason |',
      '| `:sipmap /lock` | Lock conversation |',
      '| `:sipmap /pin` | Pin to repo |',
      '| `:sipmap /duplicate #N` | Close as duplicate of #N |',
      '| `:sipmap /wontfix [reason]` | Close as won\'t fix |',
      '| `:sipmap /invalid [reason]` | Close as invalid |',
      '| `:sipmap /merge [merge|squash|rebase]` | Merge a PR |',
      '| `:sipmap /draft` | Convert PR to draft |',
      '| `:sipmap /ready` | Mark PR ready for review |',
      '| `:sipmap /rebuild` | Re-run failed CI checks |',
      '| `:sipmap /cleanup-stale` | Close stale issues (>60d) |',
      '| `:sipmap /weekly-digest` | Post weekly contributor digest |',
      '| `:sipmap /config` | Show effective config |',
      '',
      'Drop a `.sipmap.yml` in your repo to customize behavior. See [docs/config.md](https://github.com/muditagrawal2007/sipmap/blob/main/docs/config.md).',
    ].join('\n');
    await context.octokit.issues.createComment(context.issue({ body }));
  },
};
