// sipmap — created by MUDIT AGRAWAL (muditagrawal2007) — MIT licensed
// Command registry — exposes every command by name.

module.exports = {
  help: require('./help'),
  test: require('./test'),
  status: require('./status'),
  lint: require('./lint'),
  describe: require('./describe'),
  size: require('./size'),
  secrets: require('./secrets'),
  deps: require('./deps'),
  branch: require('./branch'),
  commits: require('./commits'),
  title: require('./title'),
  docs: require('./docs'),
  tests: require('./tests'),
  approvals: require('./approvals'),
  assign: require('./assign'),
  unassign: require('./unassign'),
  claim: require('./claim'),
  unclaim: require('./unclaim'),
  thanks: require('./thanks'),
  metrics: require('./metrics'),
  review: require('./review'),
  label: require('./label').label,
  unlabel: require('./label').unlabel,
  'good-first-issue': require('./label').goodFirstIssue,
  'help-wanted': require('./label').helpWanted,
  close: require('./lifecycle').close,
  reopen: require('./lifecycle').reopen,
  lock: require('./lifecycle').lock,
  pin: require('./lifecycle').pin,
  'weekly-digest': require('./weeklyDigest'),
  config: require('./config'),
};
